setup_subm.sh
=> If kubeconfig admin user not found, switch to context of master user

helper_functions, setup_subm.sh
=> Change Junit system test names to include function args

acm/downstream_deploy_bundle_acm_operator.sh
=> Split configure_submariner_for_managed_cluster() to sub functions

acm/downstream_push_bundle_to_olm_catalog.sh
=> When getting latest index-image of bundle, sort it by product version

setup_subm.sh
=> Run subctl gather within collect_submariner_info()

acm/downstream_push_bundle_to_olm_catalog.sh
Possible workaround for https://github.com/stolostron/backlog/issues/19405
=> Verify package manifest channel of bundle instead of version number

acm/downstream_deploy_bundle_acm_operator.sh, acm/downstream_push_bundle_to_olm_catalog.sh, subm_variables
=> Refactor Bundle deployment functions

acm/downstream_deploy_bundle_acm_operator.sh, acm/downstream_push_bundle_to_olm_catalog.sh
=> Fix Submariner namespace and subscription in deploy_ocp_bundle()

acm/downstream_deploy_bundle_acm_operator.sh
=> Verify SubmarinerConfig and ManagedClusterAddons readiness

setup_subm.sh
=> When cleaning Submariner CRDs do not remove ACM Submariner Addon

acm/downstream_deploy_bundle_acm_operator.sh
=> Expand SubmarinerConfig and ManagedClusterAddons verification tests

acm/downstream_deploy_bundle_acm_operator.sh
=> Skip SubmarinerAgentDegraded check, as it might indicate old state

acm/downstream_deploy_bundle_acm_operator.sh
=> Verify SubmarinerAgent & SubmarinerConnection conditions not degraded

acm/downstream_push_bundle_to_olm_catalog.sh, setup_subm.sh
- Verify that subctl shows the correct Submariner version installed
- Minor typo fix
=> Test for https://bugzilla.redhat.com/show_bug.cgi?id=2048741

acm/downstream_deploy_bundle_acm_operator.sh
=> Split validate_submariner_addon functions to better identify status

setup_subm.sh
=> Precede subctl download before ACM tests (subctl is used in teardown)

setup_subm.sh
=> Fix all usages of "ls -tu" (last accessed) to "ls -tc" (last created)

setup_subm.sh
=> Run upload_submariner_images_to_cluster_registry() only when required

setup_subm.sh
=> Option to deploy Submariner bundle without reinstalling ACM

acm/downstream_deploy_bundle_acm_operator.sh
=> Rename few functions

acm/downstream_deploy_bundle_acm_operator.sh, acm/downstream_push_bundle_to_olm_catalog.sh
=> Disable manual subscription for Submariner bundle

acm/downstream_deploy_bundle_acm_operator.sh, setup_subm.sh
=> Print ACM hub version at teardown

README.md, acm/downstream_deploy_bundle_acm_operator.sh, setup_subm.sh
=> Update Readme and other script descriptions

acm/downstream_push_bundle_to_olm_catalog.sh
=> Display OLM deployment logs more accurate

acm/downstream_deploy_bundle_acm_operator.sh, acm/downstream_push_bundle_to_olm_catalog.sh
=> Increase SubmarinerAgentDegraded condition timeout to 15 minutes

acm/downstream_deploy_bundle_acm_operator.sh
=> Force deleting managed cluster if it hangs due to finalizers

acm/downstream_deploy_bundle_acm_operator.sh, acm/downstream_push_bundle_to_olm_catalog.sh, helper_functions, setup_subm.sh, subm_variables
It seems to be ready for merge to master:
See latest test run, where the branch is working both for ACM 2.5 and Submariner 0.12:
https://qe-jenkins-csb-skynet.apps.ocp4.prod.psi.redhat.com/job/ACM-2.5.0-Submariner-0.12.0-AWS-OSP/
And also for ACM 2.4 and Submariner 0.11:
https://qe-jenkins-csb-skynet.apps.ocp4.prod.psi.redhat.com/view/ACM%202.4.2/job/ACM-2.4.2-Submariner-0.11.2-AWS-AWS/
=> Merge Acm 2.5 branch to master

helper_functions, setup_subm.sh
=> Skip gathering cluster's info if the cluster is inaccessible

acm/downstream_deploy_bundle_acm_operator.sh, setup_subm.sh
=> Add configuration for Openstack cloud prepare (supported in ACM 2.5)

acm/downstream_deploy_bundle_acm_operator.sh
=> Wait for managed cluster secret creation

setup_subm.sh
=> Test uninstall of Submariner with SubCtl

acm/downstream_deploy_bundle_acm_operator.sh, setup_subm.sh
=> Update both .sec files if empty or if modified more than 1 day ago

acm/downstream_deploy_bundle_acm_operator.sh
=> Fix missing regex to wait for ManagedCluster Opaque secret

setup_subm.sh
=> Make the uninstall and clean functions common to all clusters

setup_subm.sh
=> Update test status exit code after system tests completion

acm/downstream_deploy_bundle_acm_operator.sh, helper_functions, test_functions
=> Version check should be ignored if just destroying clusters

helper_functions, setup_subm.sh, test_functions
=> Prune old registry images after deleting images-streams

helper_functions, lib/sh2ju.sh, setup_subm.sh, test_functions
=> Mark all tests after a fatal error, as skipped in junit report

acm_functions, helper_functions, lib/sh2ju.sh, olm_functions, setup_subm.sh, subm_variables, test_functions
Recently tested and passed:
https://qe-jenkins-csb-skynet.apps.ocp-c1.prod.psi.redhat.com/job/ACM-2.6.0-Submariner-0.13.0-AWS-OSP-OVN/51/Test-Report
=> Multiple fixes

acm_functions, helper_functions, setup_subm.sh, subm_variables, test_functions
Tested on: https://qe-jenkins-csb-skynet.apps.ocp-c1.prod.psi.redhat.com/view/ACM%202.7/job/ACM-2.7.0-Submariner-0.14.1-AWS-OSP-Globalnet-OVN/111/Test-Report/
=> Fixes for installtion and cleanup on OSP cloud
